# Generated by Django 3.2.3 on 2022-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionamount',
            field=models.DecimalField(db_column='TransactionAmount', decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
